name: com.payoo.madero

on:
    push:
        branches: [main]
        paths-ignore:
          - '.env'
    pull_request:
        branches: [main]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: echo building...

    deploy-development:
        runs-on: ubuntu-latest
        environment:
            name: development
            url: ${{vars.URL}}
        needs: build
        steps:
            - name: 🔄 Sincronização do repositório
              uses: actions/checkout@v1
            - name: 📂 Envio dos arquivos ao servidor
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}
            - name: 🔒 Criação da .env de teste
              run: echo "a" > /domains/payoo.com.br/public_html/dev/.env

    deploy-staging:
        runs-on: ubuntu-latest
        environment:
            name: staging
            url: ${{vars.URL}}
        needs: deploy-development
        steps:
            - name: 🔄 Sincronização do repositório
              uses: actions/checkout@v1
            - name: 📂 Envio dos arquivos ao servidor
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}
            - name: 🔒 Criação da .env de homologação
              run: echo "${{ secrets.ENV_FINAL }}" > ${{vars.TARGET}}.env
    deploy-production:
        runs-on: ubuntu-latest
        environment:
            name: production
            url: ${{vars.URL}}
        needs: deploy-staging
        steps:
            - name: 🔄 Sincronização do repositório
              uses: actions/checkout@v1
            - name: 📂 Envio dos arquivos ao servidor
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}
            - name: 🔒 Criação da .env de homologação
              run: echo "${{ secrets.ENV_FINAL }}" > ${{vars.TARGET}}.env