name: com.payoo.madero

on:
    push:
        branches: [main]
        paths-ignore:
          - '.env'
    pull_request:
        branches: [main]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: echo building...

    deploy-development:
        runs-on: ubuntu-latest
        environment:
            name: development
            url: ${{vars.URL}}
        needs: build
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v1
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}
            - name: Create .env file
              run: |
                echo "${{ secrets.ENV_FILE }}" > .env

    deploy-staging:
        runs-on: ubuntu-latest
        environment:
            name: staging
            url: ${{vars.URL}}
        needs: deploy-development
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v1
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}
            - name: Create .env file
              uses: ozaytsev86/create-env-file@v1
              with:
                INPUT_ENV_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                INPUT_ENV_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
                INPUT_ENV_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
                INPUT_ENV_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                INPUT_ENV_GOOGLE_RECAPTCHA_SECRET_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}
    deploy-production:
        runs-on: ubuntu-latest
        environment:
            name: production
            url: ${{vars.URL}}
        needs: deploy-staging
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v1
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}
            - name: Create .env file
              uses: ozaytsev86/create-env-file@v1
              with:
                INPUT_ENV_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                INPUT_ENV_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
                INPUT_ENV_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
                INPUT_ENV_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                INPUT_ENV_GOOGLE_RECAPTCHA_SECRET_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}